Compatibility with Windows x64 data model.
libfn/functional pull request #97
Opened 2024-10-15 13:27 UTC by InCom-0

Tiny change of:
'ul' literal to 'ull' in several tests to correctly support Windows MinGW data model.

2024-10-15 14:45 UTC, Bronek commented
Thank you, I will check it out. 🙌

2024-10-15 15:06 UTC, Bronek commented
> Thank you, I will check it out. 🙌

it seems other platforms do not like it. You can fix it in other ways, or I could get rid of `std::size_t` used in literals in unit tests.

2024-10-15 16:49 UTC, InCom-0 commented
> > Thank you, I will check it out. 🙌
> 
> it seems other platforms do not like it. You can fix it in other ways, or I could get rid of `std::size_t` used in literals in unit tests.

I see ... seems strange and I naively thought that was a guaranteed fix ... but then again the intricacies of cross-platform development are well beyond my pay grade :-).

Anyway, as you say I can and know how to fix it for my purposes in my fork for the time being.

Thanks for the quick response.

2024-10-15 17:58 UTC, Bronek approved these changes
nice ! Thanks for making this project usable with mingw !

2024-10-15 18:00 UTC, Bronek requested changes
Before I merge, can you please squash these two commits into one AND please sign it with your GPG signature ? https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

2024-10-18 14:19 UTC, Bronek approved these changes

2024-10-18 14:19 UTC, merged